"""Add print status tracking to waybill_prints table

Revision ID: 6fc54b2588d8
Revises: d1e2f3g4h5i6
Create Date: 2025-11-16 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc54b2588d8'
down_revision = 'd1e2f3g4h5i6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_prints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('print_status', sa.String(), nullable=True, server_default='idle'))
        batch_op.add_column(sa.Column('cups_job_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('printer_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('print_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('print_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_prints', schema=None) as batch_op:
        batch_op.drop_column('print_completed_at')
        batch_op.drop_column('print_error')
        batch_op.drop_column('printer_name')
        batch_op.drop_column('cups_job_id')
        batch_op.drop_column('print_status')
    # ### end Alembic commands ###

