"""Add auto_print flag to waybill_prints table

Revision ID: a1b2c3d4e5f6
Revises: 6fc54b2588d8
Create Date: 2025-11-29 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '6fc54b2588d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_prints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_print', sa.Boolean(), nullable=True, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_prints', schema=None) as batch_op:
        batch_op.drop_column('auto_print')
    # ### end Alembic commands ###

