"""Add Download Related Columns to Waybill Print Table

Revision ID: b823eb6c8403
Revises: 0f2ae1ebaada
Create Date: 2025-10-24 19:02:25.048943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b823eb6c8403'
down_revision = '0f2ae1ebaada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_prints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), server_default='pending', nullable=True))
        batch_op.add_column(sa.Column('local_file_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('downloaded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_prints', schema=None) as batch_op:
        batch_op.drop_column('downloaded_at')
        batch_op.drop_column('error_message')
        batch_op.drop_column('local_file_path')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
