"""Add tenant_id to waybill_prints table

Revision ID: c9f3a7d2b1e5
Revises: b823eb6c8403
Create Date: 2025-11-14 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f3a7d2b1e5'
down_revision = 'b823eb6c8403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_prints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False, server_default='1'))
    
    # Remove server_default after adding the column to make it truly required
    with op.batch_alter_table('waybill_prints', schema=None) as batch_op:
        batch_op.alter_column('tenant_id', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_prints', schema=None) as batch_op:
        batch_op.drop_column('tenant_id')
    # ### end Alembic commands ###

