"""Add marketplace to waybill_prints table

Revision ID: d1e2f3g4h5i6
Revises: c9f3a7d2b1e5
Create Date: 2025-11-14 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e2f3g4h5i6'
down_revision = 'c9f3a7d2b1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_prints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketplace', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_prints', schema=None) as batch_op:
        batch_op.drop_column('marketplace')
    # ### end Alembic commands ###

