#!/bin/bash
# Docker startup script with dynamic IP detection

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}🚀 Starting RPI Waybill Printer with Docker${NC}\n"

# Detect local IP address
echo -e "${YELLOW}Detecting local IP address...${NC}"

if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    LOCAL_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n 1)
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux/Raspberry Pi
    LOCAL_IP=$(hostname -I | awk '{print $1}')
else
    LOCAL_IP="localhost"
fi

if [ -z "$LOCAL_IP" ]; then
    echo -e "${YELLOW}⚠️  Could not detect IP, using localhost${NC}"
    LOCAL_IP="localhost"
else
    echo -e "${GREEN}✅ Detected IP: $LOCAL_IP${NC}"
fi

# Generate frontend .env file with detected IP
echo -e "${YELLOW}Generating frontend/.env with detected IP...${NC}"
cat > frontend/.env <<EOF
# Frontend Configuration - Auto-generated by docker-start-dynamic.sh
# API URL for the React frontend
# Generated at: $(date)
VITE_API_URL=http://${LOCAL_IP}:5000
VITE_BASE_URL=http://${LOCAL_IP}:5000
EOF

echo -e "${GREEN}✅ Generated frontend/.env:${NC}"
cat frontend/.env
echo ""

# Determine which compose file to use
COMPOSE_FILE="docker-compose.yml"
if [ "$1" == "dev" ]; then
    COMPOSE_FILE="docker-compose.dev.yml"
    echo -e "${BLUE}Using development configuration${NC}"
elif [ "$1" == "prod" ]; then
    COMPOSE_FILE="docker-compose.prod.yml"
    echo -e "${BLUE}Using production configuration${NC}"
else
    echo -e "${BLUE}Using default configuration${NC}"
fi

# Start Docker containers
echo -e "${YELLOW}Starting Docker containers...${NC}"
if [ "$2" == "--build" ]; then
    docker compose -f $COMPOSE_FILE up -d --build
else
    docker compose -f $COMPOSE_FILE up -d
fi

echo ""
echo -e "${GREEN}✅ Containers started!${NC}"
echo -e "${BLUE}Access the application at:${NC}"
echo -e "  Frontend: http://${LOCAL_IP}:5173"
echo -e "  Backend:  http://${LOCAL_IP}:5000"
echo ""
echo -e "${BLUE}Commands:${NC}"
echo -e "  View logs:    docker compose -f $COMPOSE_FILE logs -f"
echo -e "  Stop:         docker compose -f $COMPOSE_FILE down"
echo -e "  Restart:      docker compose -f $COMPOSE_FILE restart"
