#!/bin/bash

# Docker Setup for Raspberry Pi
# This script installs Docker and configures it to auto-start containers on boot

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}🐳 Setting up Docker for RPI Waybill Printer${NC}\n"

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Docker not found. Installing Docker...${NC}"
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    sudo rm get-docker.sh
    echo -e "${GREEN}✅ Docker installed${NC}"
else
    echo -e "${GREEN}✅ Docker already installed${NC}"
fi

# Check if Docker Compose is installed
if ! command -v docker compose &> /dev/null; then
    echo -e "${YELLOW}Docker Compose plugin not found. Installing...${NC}"
    sudo apt-get update
    sudo apt-get install -y docker-compose-plugin
    echo -e "${GREEN}✅ Docker Compose installed${NC}"
else
    echo -e "${GREEN}✅ Docker Compose already installed${NC}"
fi

# Add current user to docker group
ACTUAL_USER=${SUDO_USER:-$(whoami)}
echo -e "${YELLOW}Adding user $ACTUAL_USER to docker group...${NC}"
sudo usermod -aG docker "$ACTUAL_USER"
echo -e "${GREEN}✅ User added to docker group (logout required to take effect)${NC}"

# Enable Docker service to start on boot
echo -e "${YELLOW}Enabling Docker service to start on boot...${NC}"
sudo systemctl enable docker
sudo systemctl start docker
echo -e "${GREEN}✅ Docker service enabled and started${NC}"

# Project directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo -e "\n${BLUE}📝 Configuring Dynamic IP for Frontend${NC}"

# Detect local IP address
echo -e "${YELLOW}Detecting local IP address...${NC}"
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    LOCAL_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n 1)
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux/Raspberry Pi
    LOCAL_IP=$(hostname -I | awk '{print $1}')
else
    LOCAL_IP="localhost"
fi

if [ -z "$LOCAL_IP" ]; then
    echo -e "${YELLOW}⚠️  Could not detect IP, using localhost${NC}"
    LOCAL_IP="localhost"
else
    echo -e "${GREEN}✅ Detected IP: $LOCAL_IP${NC}"
fi

# Generate frontend .env file with detected IP
echo -e "${YELLOW}Generating frontend/.env with detected IP...${NC}"
cat > "$PROJECT_DIR/frontend/.env" <<EOF
# Frontend Configuration - Auto-generated by installers/docker.sh
# API URL for the React frontend
# Generated at: $(date)
VITE_API_URL=http://${LOCAL_IP}:5000
VITE_BASE_URL=http://${LOCAL_IP}:5000
EOF

echo -e "${GREEN}✅ Generated frontend/.env with IP: $LOCAL_IP${NC}\n"

echo -e "${BLUE}📝 Docker Auto-start Configuration${NC}"
echo -e "${YELLOW}Your docker-compose.yml already has 'restart: unless-stopped'${NC}"
echo -e "${YELLOW}This means containers will automatically restart on boot.${NC}\n"

echo -e "${GREEN}✅ Docker setup complete!${NC}\n"

echo -e "${BLUE}Next Steps:${NC}"
echo -e "  1. Logout and login again (for docker group to take effect)"
echo -e "  2. Navigate to project: cd $PROJECT_DIR"
echo -e "  3. Build and start containers:"
echo -e "     ${YELLOW}docker compose -f docker-compose.prod.yml up -d --build${NC}"
echo -e ""
echo -e "${BLUE}Access Your Application:${NC}"
echo -e "  • Frontend: ${GREEN}http://${LOCAL_IP}:5173${NC}"
echo -e "  • Backend:  ${GREEN}http://${LOCAL_IP}:5000${NC}"
echo -e ""
echo -e "${BLUE}Container Management:${NC}"
echo -e "  • Start: ${YELLOW}docker compose -f docker-compose.prod.yml up -d${NC}"
echo -e "  • Stop: ${YELLOW}docker compose -f docker-compose.prod.yml down${NC}"
echo -e "  • View logs: ${YELLOW}docker compose -f docker-compose.prod.yml logs -f${NC}"
echo -e "  • Restart: ${YELLOW}docker compose -f docker-compose.prod.yml restart${NC}"
echo -e "  • Status: ${YELLOW}docker compose -f docker-compose.prod.yml ps${NC}"
