"""Add file tracking and error fields to waybill_print_jobs

Revision ID: add_file_tracking_fields
Revises: e9d032604bab
Create Date: 2025-10-17 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_file_tracking_fields'
down_revision = 'e9d032604bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_print_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('download_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_print_jobs', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('download_started_at')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
