"""Add download_completed_at field for auditing

Revision ID: add_download_completed_at
Revises: add_file_tracking_fields
Create Date: 2025-10-17 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_download_completed_at'
down_revision = 'add_file_tracking_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_print_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_print_jobs', schema=None) as batch_op:
        batch_op.drop_column('download_completed_at')

    # ### end Alembic commands ###
