"""Add printer tracking fields to waybill_print_jobs

Revision ID: c1a2b3c4d5e6
Revises: b6fda062bdbf
Create Date: 2025-10-18 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a2b3c4d5e6'
down_revision = 'b6fda062bdbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_print_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('print_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('print_completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('print_status', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_print_jobs', schema=None) as batch_op:
        batch_op.drop_column('print_status')
        batch_op.drop_column('print_completed_at')
        batch_op.drop_column('print_started_at')

    # ### end Alembic commands ###
