"""create_waybill_print_jobs_table

Revision ID: e9d032604bab
Revises: 
Create Date: 2025-10-16 13:19:59.048448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d032604bab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waybill_print_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('invoice_number', sa.String(length=255), nullable=False),
    sa.Column('waybill_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('download_started_at', sa.DateTime(), nullable=True),
    sa.Column('download_completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'invoice_number', 'waybill_url', name='uq_waybill_print_jobs_tenant_invoice_url')
    )
    with op.batch_alter_table('waybill_print_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waybill_print_jobs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waybill_print_jobs_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_waybill_print_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_print_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waybill_print_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_waybill_print_jobs_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_waybill_print_jobs_tenant_id'))

    op.drop_table('waybill_print_jobs')
    # ### end Alembic commands ###
