"""Remove unique constraint to allow duplicate print jobs

Revision ID: fa1408fe00e5
Revises: c1a2b3c4d5e6
Create Date: 2025-10-18 10:23:08.389471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1408fe00e5'
down_revision = 'c1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_print_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_waybill_print_jobs_tenant_invoice_url'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_print_jobs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_waybill_print_jobs_tenant_invoice_url'), ['tenant_id', 'invoice_number', 'waybill_url'])

    # ### end Alembic commands ###
